import localFont from "next/font/local";
import "./globals.css";
import { Providers } from "@/context/provider";
// import Header from "@/layout/header/header";
// import Footer from "@/layout/footer/footer";
// import { Provider } from "react-redux";
// import store from "@/redux/store/store";
import PagesLayout from "@/components/layoutWrapper/layoutWrapper";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          {/* <Provider store={store}> */}
            {/* <Header  /> */}
            <PagesLayout >
            {children}
          {/* </Provider> */}
          </PagesLayout>
        </Providers>

        {/* <Footer /> */}
      </body>
    </html>
  );
}
